In [2]:
!rm -rf /content/repo
!git clone -q https://github.com/Udrasht/Hindi-Sentiment-Analysis-Corpus-from-Amazon-Reviews.git /content/repo
!cp /content/repo/data/train.xlsx /content/repo/data/test.xlsx /content/
!ls /content

repo  sample_data  test.xlsx  train.xlsx

In [3]:
import pandas as pd

In [4]:
df1 = pd.read_excel('train.xlsx')
df1.head()

,index,title_hindi,content_hindi,rating,labels
0,1,पहले दिन काम नहीं हुआ,"लोहा काम नहीं कर रहा है, गर्म नहीं हो रहा है",2,Negative
1,2,चार्ज बहुत जल्दी खत्म हो जाता है,मुझे डिज़ाइन पसंद है और कोई शोर नहीं है। लेकिन...,2,Negative
2,3,उत्पाद ने दो सप्ताह में काम करना बंद कर दिया,मैं किसी को भी इस ब्रश की अनुशंसा नहीं करूंगा।...,2,Negative
3,4,उतरते समय चार्ज करना,"उत्पाद अच्छा था, चार्जिंग बहुत खराब थी, हमने फ...",3,Neutral
4,5,ख़राब गुणवत्ता वाला माउस,इस बार विक्रेता द्वारा आपूर्ति किये गये चूहों ...,2,Negative

In [5]:
df1_test = pd.read_excel('test.xlsx')
df1_test.head()

,index,title_hindi,content_hindi,rating,labels
0,1,स्क्रॉल बटन ने 14 दिनों के बाद काम करना बंद कर...,खरीदारी के मात्र 14 दिन बाद स्क्रॉलिंग बटन ने ...,1,Negative
1,2,खराब क्वालिटी,इसका कोई मूल्य नहीं है. अच्छे उत्पाद ही खरीदें...,1,Negative
2,3,मैं आपको तुरंत चेतावनी देता हूं कि इस उत्पाद क...,मीडिया लोड नहीं किया जा सका. कई ग्राहकों को क्...,1,Negative
3,4,पैसे की बर्बादी मत खरीदो ð¯,पैसे की बर्बादी मत खरीदो ð¯,1,Negative
4,5,4 महीने से काम भी नहीं,4 महीने बाद भी ब्लूटूथ काम नहीं कर रहा है,1,Negative

In [6]:

# Define a function to map values
def map_values(value):
    if value in [1, 2]:
        return "negative"
    elif value == 3:
        return "neutral"
    elif value in [4, 5]:
        return "positive"
    else:
        return value

# Apply the function to the column
df1['new_rating'] = df1['rating'].apply(map_values)
df1_test['new_rating'] = df1_test['rating'].apply(map_values)

In [7]:
df1.head()

,index,title_hindi,content_hindi,rating,labels,new_rating
0,1,पहले दिन काम नहीं हुआ,"लोहा काम नहीं कर रहा है, गर्म नहीं हो रहा है",2,Negative,negative
1,2,चार्ज बहुत जल्दी खत्म हो जाता है,मुझे डिज़ाइन पसंद है और कोई शोर नहीं है। लेकिन...,2,Negative,negative
2,3,उत्पाद ने दो सप्ताह में काम करना बंद कर दिया,मैं किसी को भी इस ब्रश की अनुशंसा नहीं करूंगा।...,2,Negative,negative
3,4,उतरते समय चार्ज करना,"उत्पाद अच्छा था, चार्जिंग बहुत खराब थी, हमने फ...",3,Neutral,neutral
4,5,ख़राब गुणवत्ता वाला माउस,इस बार विक्रेता द्वारा आपूर्ति किये गये चूहों ...,2,Negative,negative

In [8]:
df1_test.head()

,index,title_hindi,content_hindi,rating,labels,new_rating
0,1,स्क्रॉल बटन ने 14 दिनों के बाद काम करना बंद कर...,खरीदारी के मात्र 14 दिन बाद स्क्रॉलिंग बटन ने ...,1,Negative,negative
1,2,खराब क्वालिटी,इसका कोई मूल्य नहीं है. अच्छे उत्पाद ही खरीदें...,1,Negative,negative
2,3,मैं आपको तुरंत चेतावनी देता हूं कि इस उत्पाद क...,मीडिया लोड नहीं किया जा सका. कई ग्राहकों को क्...,1,Negative,negative
3,4,पैसे की बर्बादी मत खरीदो ð¯,पैसे की बर्बादी मत खरीदो ð¯,1,Negative,negative
4,5,4 महीने से काम भी नहीं,4 महीने बाद भी ब्लूटूथ काम नहीं कर रहा है,1,Negative,negative

In [9]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.feature_extraction.text import TfidfVectorizer

X_train = df1['title_hindi']
y_train = df1['new_rating']

X_test = df1_test['title_hindi']
y_test = df1_test['new_rating']
# Convert text data into numerical features using TfidfVectorizer for unigram
vectorizer_unigram = TfidfVectorizer()
X_train_unigram = vectorizer_unigram.fit_transform(X_train)
X_test_unigram = vectorizer_unigram.transform(X_test)

# Train Multinomial Naive Bayes model on unigram features
nb_unigram = MultinomialNB()
nb_unigram.fit(X_train_unigram, y_train)

# Predict on test set
y_pred_unigram = nb_unigram.predict(X_test_unigram)

# Calculate accuracy for unigram
accuracy_unigram = accuracy_score(y_test, y_pred_unigram)
print("Accuracy for unigram using TFidf:", accuracy_unigram)
print(classification_report(y_test, y_pred_unigram))

# Repeat the same process for bigram
# Convert text data into numerical features using TfidfVectorizer for bigram
vectorizer_bigram = TfidfVectorizer(ngram_range=(2, 2))
X_train_bigram = vectorizer_bigram.fit_transform(X_train)
X_test_bigram = vectorizer_bigram.transform(X_test)

# Train Multinomial Naive Bayes model on bigram features
nb_bigram = MultinomialNB()
nb_bigram.fit(X_train_bigram, y_train)

# Predict on test set
y_pred_bigram = nb_bigram.predict(X_test_bigram)

# Calculate accuracy for bigram
accuracy_bigram = accuracy_score(y_test, y_pred_bigram)
print("Accuracy for bigram using TFidf:", accuracy_bigram)
print(classification_report(y_test, y_pred_bigram))

Accuracy for unigram using TFidf: 0.6640271493212669
              precision    recall  f1-score   support

    negative       0.64      0.88      0.74       394
     neutral       0.62      0.05      0.09       170
    positive       0.71      0.73      0.72       320

    accuracy                           0.66       884
   macro avg       0.65      0.55      0.51       884
weighted avg       0.66      0.66      0.61       884

Accuracy for bigram using TFidf: 0.6493212669683258
              precision    recall  f1-score   support

    negative       0.60      0.94      0.73       394
     neutral       0.89      0.05      0.09       170
    positive       0.77      0.61      0.68       320

    accuracy                           0.65       884
   macro avg       0.75      0.53      0.50       884
weighted avg       0.72      0.65      0.59       884

In [10]:

X_train = df1['title_hindi']
y_train = df1['new_rating']

X_test = df1_test['title_hindi']
y_test = df1_test['new_rating']
# 1. Convert text data into numerical features using CountVectorizer for unigram
vectorizer_unigram = CountVectorizer()
X_train_unigram = vectorizer_unigram.fit_transform(X_train)
X_test_unigram = vectorizer_unigram.transform(X_test)

# 2. Train Multinomial Naive Bayes model on unigram features
nb_unigram = MultinomialNB()
nb_unigram.fit(X_train_unigram, y_train)

# Predict on test set
y_pred_unigram = nb_unigram.predict(X_test_unigram)

# Calculate accuracy for unigram
accuracy_unigram = accuracy_score(y_test, y_pred_unigram)
print("Accuracy for unigram using Bag of Words:", accuracy_unigram)
print(classification_report(y_test, y_pred_unigram))

# Repeat the same process for bigram
# 1. Convert text data into numerical features using CountVectorizer for bigram
vectorizer_bigram = CountVectorizer(ngram_range=(2, 2))
X_train_bigram = vectorizer_bigram.fit_transform(X_train)
X_test_bigram = vectorizer_bigram.transform(X_test)

# 2. Train Multinomial Naive Bayes model on bigram features
nb_bigram = MultinomialNB()
nb_bigram.fit(X_train_bigram, y_train)

# Predict on test set
y_pred_bigram = nb_bigram.predict(X_test_bigram)

# Calculate accuracy for bigram
accuracy_bigram = accuracy_score(y_test, y_pred_bigram)
print("Accuracy for bigram using Bag of Words:", accuracy_bigram)
print(classification_report(y_test, y_pred_bigram))

Accuracy for unigram using Bag of Words: 0.6628959276018099
              precision    recall  f1-score   support

    negative       0.66      0.82      0.73       394
     neutral       0.42      0.17      0.24       170
    positive       0.72      0.73      0.73       320

    accuracy                           0.66       884
   macro avg       0.60      0.57      0.57       884
weighted avg       0.63      0.66      0.64       884

Accuracy for bigram using Bag of Words: 0.6357466063348416
              precision    recall  f1-score   support

    negative       0.60      0.90      0.72       394
     neutral       0.45      0.11      0.17       170
    positive       0.75      0.59      0.66       320

    accuracy                           0.64       884
   macro avg       0.60      0.53      0.52       884
weighted avg       0.62      0.64      0.59       884

In [11]:

X_train = df1['content_hindi']
y_train = df1['new_rating']

X_test = df1_test['content_hindi']
y_test = df1_test['new_rating']
#  Convert text data into numerical features using TfidfVectorizer for unigram
vectorizer_unigram = TfidfVectorizer()
X_train_unigram = vectorizer_unigram.fit_transform(X_train)
X_test_unigram = vectorizer_unigram.transform(X_test)

#  Train Multinomial Naive Bayes model on unigram features
nb_unigram = MultinomialNB()
nb_unigram.fit(X_train_unigram, y_train)

# Predict on test set
y_pred_unigram = nb_unigram.predict(X_test_unigram)

# Calculate accuracy for unigram
accuracy_unigram = accuracy_score(y_test, y_pred_unigram)
print("Accuracy for unigram using TFidf:", accuracy_unigram)
print(classification_report(y_test, y_pred_unigram))

# Repeat the same process for bigram
#  Convert text data into numerical features using TfidfVectorizer for bigram
vectorizer_bigram = TfidfVectorizer(ngram_range=(2, 2))
X_train_bigram = vectorizer_bigram.fit_transform(X_train)
X_test_bigram = vectorizer_bigram.transform(X_test)

#  Train Multinomial Naive Bayes model on bigram features
nb_bigram = MultinomialNB()
nb_bigram.fit(X_train_bigram, y_train)

# Predict on test set
y_pred_bigram = nb_bigram.predict(X_test_bigram)

# Calculate accuracy for bigram
accuracy_bigram = accuracy_score(y_test, y_pred_bigram)
print("Accuracy for bigram using TFidf:", accuracy_bigram)
print(classification_report(y_test, y_pred_bigram))

Accuracy for unigram using TFidf: 0.6527149321266968
              precision    recall  f1-score   support

    negative       0.63      0.91      0.74       394
     neutral       0.00      0.00      0.00       170
    positive       0.70      0.68      0.69       320

    accuracy                           0.65       884
   macro avg       0.44      0.53      0.48       884
weighted avg       0.53      0.65      0.58       884

/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Accuracy for bigram using TFidf: 0.670814479638009
              precision    recall  f1-score   support

    negative       0.61      0.94      0.74       394
     neutral       1.00      0.02      0.05       170
    positive       0.80      0.68      0.74       320

    accuracy                           0.67       884
   macro avg       0.80      0.55      0.51       884
weighted avg       0.76      0.67      0.61       884

In [12]:

X_train = df1['content_hindi']
y_train = df1['new_rating']

X_test = df1_test['content_hindi']
y_test = df1_test['new_rating']
#  Convert text data into numerical features using CountVectorizer for unigram
vectorizer_unigram = CountVectorizer()
X_train_unigram = vectorizer_unigram.fit_transform(X_train)
X_test_unigram = vectorizer_unigram.transform(X_test)

#  Train Multinomial Naive Bayes model on unigram features
nb_unigram = MultinomialNB()
nb_unigram.fit(X_train_unigram, y_train)

# Predict on test set
y_pred_unigram = nb_unigram.predict(X_test_unigram)

# Calculate accuracy for unigram
accuracy_unigram = accuracy_score(y_test, y_pred_unigram)
print("Accuracy for unigram using Bag of Words:", accuracy_unigram)
print(classification_report(y_test, y_pred_unigram))

# Repeat the same process for bigram
#  Convert text data into numerical features using CountVectorizer for bigram
vectorizer_bigram = CountVectorizer(ngram_range=(2, 2))
X_train_bigram = vectorizer_bigram.fit_transform(X_train)
X_test_bigram = vectorizer_bigram.transform(X_test)

# Train Multinomial Naive Bayes model on bigram features
nb_bigram = MultinomialNB()
nb_bigram.fit(X_train_bigram, y_train)

# Predict on test set
y_pred_bigram = nb_bigram.predict(X_test_bigram)

# Calculate accuracy for bigram
accuracy_bigram = accuracy_score(y_test, y_pred_bigram)
print("Accuracy for bigram using Bag of Words:", accuracy_bigram)
print(classification_report(y_test, y_pred_bigram))

Accuracy for unigram using Bag of Words: 0.6187782805429864
              precision    recall  f1-score   support

    negative       0.65      0.78      0.71       394
     neutral       0.28      0.13      0.18       170
    positive       0.65      0.68      0.66       320

    accuracy                           0.62       884
   macro avg       0.53      0.53      0.52       884
weighted avg       0.58      0.62      0.59       884

Accuracy for bigram using Bag of Words: 0.6900452488687783
              precision    recall  f1-score   support

    negative       0.67      0.86      0.76       394
     neutral       0.59      0.14      0.23       170
    positive       0.73      0.78      0.75       320

    accuracy                           0.69       884
   macro avg       0.66      0.59      0.58       884
weighted avg       0.68      0.69      0.65       884

In [13]:
df1['concatenated'] = df1['title_hindi'] + ' ' + df1['content_hindi']
df1_test['concatenated'] = df1_test['title_hindi'] + ' ' + df1_test['content_hindi']

In [14]:

X_train = df1['concatenated'] # Your text data
y_train = df1['new_rating']  # Corresponding classes

X_test = df1_test['concatenated']
y_test = df1_test['new_rating']
#  Convert text data into numerical features using TfidfVectorizer for unigram
vectorizer_unigram = TfidfVectorizer()
X_train_unigram = vectorizer_unigram.fit_transform(X_train)
X_test_unigram = vectorizer_unigram.transform(X_test)

#  Train Multinomial Naive Bayes model on unigram features
nb_unigram = MultinomialNB()
nb_unigram.fit(X_train_unigram, y_train)

# Predict on test set
y_pred_unigram = nb_unigram.predict(X_test_unigram)

# Calculate accuracy for unigram
accuracy_unigram = accuracy_score(y_test, y_pred_unigram)
print("Accuracy for unigram using TFidf:", accuracy_unigram)
print(classification_report(y_test, y_pred_unigram))

# Repeat the same process for bigram
#  Convert text data into numerical features using TfidfVectorizer for bigram
vectorizer_bigram = TfidfVectorizer(ngram_range=(2, 2))
X_train_bigram = vectorizer_bigram.fit_transform(X_train)
X_test_bigram = vectorizer_bigram.transform(X_test)

#  Train Multinomial Naive Bayes model on bigram features
nb_bigram = MultinomialNB()
nb_bigram.fit(X_train_bigram, y_train)

# Predict on test set
y_pred_bigram = nb_bigram.predict(X_test_bigram)

# Calculate accuracy for bigram
accuracy_bigram = accuracy_score(y_test, y_pred_bigram)
print("Accuracy for bigram using TFidf:", accuracy_bigram)
print(classification_report(y_test, y_pred_bigram))

Accuracy for unigram using TFidf: 0.6776018099547512
              precision    recall  f1-score   support

    negative       0.64      0.92      0.76       394
     neutral       0.00      0.00      0.00       170
    positive       0.74      0.73      0.74       320

    accuracy                           0.68       884
   macro avg       0.46      0.55      0.50       884
weighted avg       0.55      0.68      0.60       884

/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Accuracy for bigram using TFidf: 0.7104072398190046
              precision    recall  f1-score   support

    negative       0.64      0.95      0.77       394
     neutral       1.00      0.02      0.03       170
    positive       0.84      0.78      0.81       320

    accuracy                           0.71       884
   macro avg       0.83      0.58      0.54       884
weighted avg       0.78      0.71      0.64       884

In [15]:

X_train = df1['concatenated']
y_train = df1['new_rating']

X_test = df1_test['concatenated']
y_test = df1_test['new_rating']
#  Convert text data into numerical features using CountVectorizer for unigram
vectorizer_unigram = CountVectorizer()
X_train_unigram = vectorizer_unigram.fit_transform(X_train)
X_test_unigram = vectorizer_unigram.transform(X_test)

# Train Multinomial Naive Bayes model on unigram features
nb_unigram = MultinomialNB()
nb_unigram.fit(X_train_unigram, y_train)

# Predict on test set
y_pred_unigram = nb_unigram.predict(X_test_unigram)

# Calculate accuracy for unigram
accuracy_unigram = accuracy_score(y_test, y_pred_unigram)
print("Accuracy for unigram using Bag of Words:", accuracy_unigram)
print(classification_report(y_test, y_pred_unigram))

# Repeat the same process for bigram
# Convert text data into numerical features using CountVectorizer for bigram
vectorizer_bigram = CountVectorizer(ngram_range=(2, 2))
X_train_bigram = vectorizer_bigram.fit_transform(X_train)
X_test_bigram = vectorizer_bigram.transform(X_test)

# Train Multinomial Naive Bayes model on bigram features
nb_bigram = MultinomialNB()
nb_bigram.fit(X_train_bigram, y_train)

# Predict on test set
y_pred_bigram = nb_bigram.predict(X_test_bigram)

# Calculate accuracy for bigram
accuracy_bigram = accuracy_score(y_test, y_pred_bigram)
print("Accuracy for bigram using Bag of Words:", accuracy_bigram)
print(classification_report(y_test, y_pred_bigram))

Accuracy for unigram using Bag of Words: 0.6606334841628959
              precision    recall  f1-score   support

    negative       0.68      0.79      0.74       394
     neutral       0.35      0.20      0.25       170
    positive       0.72      0.74      0.73       320

    accuracy                           0.66       884
   macro avg       0.58      0.58      0.57       884
weighted avg       0.63      0.66      0.64       884

Accuracy for bigram using Bag of Words: 0.7262443438914027
              precision    recall  f1-score   support

    negative       0.71      0.88      0.79       394
     neutral       0.62      0.14      0.23       170
    positive       0.76      0.84      0.80       320

    accuracy                           0.73       884
   macro avg       0.70      0.62      0.61       884
weighted avg       0.71      0.73      0.68       884