In [2]:
!rm -rf /content/repo
!git clone -q https://github.com/Udrasht/Hindi-Sentiment-Analysis-Corpus-from-Amazon-Reviews.git /content/repo
!cp /content/repo/data/train.xlsx /content/repo/data/test.xlsx /content/
!ls /content

repo  sample_data  test.xlsx  train.xlsx

In [3]:
import pandas as pd

In [4]:
df1 = pd.read_excel('train.xlsx')
df1.head()

,index,title_hindi,content_hindi,rating,labels
0,1,पहले दिन काम नहीं हुआ,"लोहा काम नहीं कर रहा है, गर्म नहीं हो रहा है",2,Negative
1,2,चार्ज बहुत जल्दी खत्म हो जाता है,मुझे डिज़ाइन पसंद है और कोई शोर नहीं है। लेकिन...,2,Negative
2,3,उत्पाद ने दो सप्ताह में काम करना बंद कर दिया,मैं किसी को भी इस ब्रश की अनुशंसा नहीं करूंगा।...,2,Negative
3,4,उतरते समय चार्ज करना,"उत्पाद अच्छा था, चार्जिंग बहुत खराब थी, हमने फ...",3,Neutral
4,5,ख़राब गुणवत्ता वाला माउस,इस बार विक्रेता द्वारा आपूर्ति किये गये चूहों ...,2,Negative

In [5]:
df1_test = pd.read_excel('test.xlsx')
df1_test.head()

,index,title_hindi,content_hindi,rating,labels
0,1,स्क्रॉल बटन ने 14 दिनों के बाद काम करना बंद कर...,खरीदारी के मात्र 14 दिन बाद स्क्रॉलिंग बटन ने ...,1,Negative
1,2,खराब क्वालिटी,इसका कोई मूल्य नहीं है. अच्छे उत्पाद ही खरीदें...,1,Negative
2,3,मैं आपको तुरंत चेतावनी देता हूं कि इस उत्पाद क...,मीडिया लोड नहीं किया जा सका. कई ग्राहकों को क्...,1,Negative
3,4,पैसे की बर्बादी मत खरीदो ð¯,पैसे की बर्बादी मत खरीदो ð¯,1,Negative
4,5,4 महीने से काम भी नहीं,4 महीने बाद भी ब्लूटूथ काम नहीं कर रहा है,1,Negative

In [6]:
# Define a function to map values
def map_values(value):
    if value in [1, 2]:
        return "negative"
    elif value == 3:
        return "neutral"
    elif value in [4, 5]:
        return "positive"
    else:
        return value

# Apply the function to the column
df1['new_rating'] = df1['rating'].apply(map_values)
df1_test['new_rating'] = df1_test['rating'].apply(map_values)

In [7]:
df1.head()

,index,title_hindi,content_hindi,rating,labels,new_rating
0,1,पहले दिन काम नहीं हुआ,"लोहा काम नहीं कर रहा है, गर्म नहीं हो रहा है",2,Negative,negative
1,2,चार्ज बहुत जल्दी खत्म हो जाता है,मुझे डिज़ाइन पसंद है और कोई शोर नहीं है। लेकिन...,2,Negative,negative
2,3,उत्पाद ने दो सप्ताह में काम करना बंद कर दिया,मैं किसी को भी इस ब्रश की अनुशंसा नहीं करूंगा।...,2,Negative,negative
3,4,उतरते समय चार्ज करना,"उत्पाद अच्छा था, चार्जिंग बहुत खराब थी, हमने फ...",3,Neutral,neutral
4,5,ख़राब गुणवत्ता वाला माउस,इस बार विक्रेता द्वारा आपूर्ति किये गये चूहों ...,2,Negative,negative

In [8]:
df1_test.head()

,index,title_hindi,content_hindi,rating,labels,new_rating
0,1,स्क्रॉल बटन ने 14 दिनों के बाद काम करना बंद कर...,खरीदारी के मात्र 14 दिन बाद स्क्रॉलिंग बटन ने ...,1,Negative,negative
1,2,खराब क्वालिटी,इसका कोई मूल्य नहीं है. अच्छे उत्पाद ही खरीदें...,1,Negative,negative
2,3,मैं आपको तुरंत चेतावनी देता हूं कि इस उत्पाद क...,मीडिया लोड नहीं किया जा सका. कई ग्राहकों को क्...,1,Negative,negative
3,4,पैसे की बर्बादी मत खरीदो ð¯,पैसे की बर्बादी मत खरीदो ð¯,1,Negative,negative
4,5,4 महीने से काम भी नहीं,4 महीने बाद भी ब्लूटूथ काम नहीं कर रहा है,1,Negative,negative

In [9]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.pipeline import make_pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import classification_report


X_train = df1['title_hindi']
y_train = df1['new_rating']
X_test = df1_test['title_hindi']
y_test = df1_test['new_rating']

# Define pipelines for unigram and bigram features
unigram_pipeline = make_pipeline(TfidfVectorizer(ngram_range=(1, 1)), LogisticRegression(max_iter=1000))
bigram_pipeline = make_pipeline(TfidfVectorizer(ngram_range=(2, 2)), LogisticRegression(max_iter=1000))

# Fit and predict using unigram features
unigram_pipeline.fit(X_train, y_train)
unigram_predictions = unigram_pipeline.predict(X_test)
unigram_accuracy = accuracy_score(y_test, unigram_predictions)

print("Accuracy for unigram using Tfidf:", unigram_accuracy)
print(classification_report(y_test,unigram_predictions))

# Fit and predict using bigram features
bigram_pipeline.fit(X_train, y_train)
bigram_predictions = bigram_pipeline.predict(X_test)
bigram_accuracy = accuracy_score(y_test, bigram_predictions)

print("Accuracy for bigram using Tfidf:", bigram_accuracy)
print(classification_report(y_test,bigram_predictions))

Accuracy for unigram using Tfidf: 0.6843891402714932
              precision    recall  f1-score   support

    negative       0.67      0.85      0.75       394
     neutral       0.50      0.14      0.21       170
    positive       0.73      0.78      0.75       320

    accuracy                           0.68       884
   macro avg       0.63      0.59      0.57       884
weighted avg       0.66      0.68      0.65       884

Accuracy for bigram using Tfidf: 0.6527149321266968
              precision    recall  f1-score   support

    negative       0.61      0.93      0.73       394
     neutral       0.58      0.11      0.19       170
    positive       0.77      0.60      0.68       320

    accuracy                           0.65       884
   macro avg       0.65      0.55      0.53       884
weighted avg       0.66      0.65      0.61       884

In [10]:
X_train = df1['title_hindi']
y_train = df1['new_rating']
X_test = df1_test['title_hindi']
y_test = df1_test['new_rating']

# Define pipelines for unigram and bigram features
unigram_pipeline = make_pipeline(CountVectorizer(ngram_range=(1, 1)), LogisticRegression(max_iter=1000))
bigram_pipeline = make_pipeline(CountVectorizer(ngram_range=(2, 2)), LogisticRegression(max_iter=1000))

# Fit and predict using unigram features
unigram_pipeline.fit(X_train, y_train)
unigram_predictions = unigram_pipeline.predict(X_test)
unigram_accuracy = accuracy_score(y_test, unigram_predictions)

print("Accuracy for unigram using Bag of words:", unigram_accuracy)
print(classification_report(y_test,unigram_predictions))

# Fit and predict using bigram features
bigram_pipeline.fit(X_train, y_train)
bigram_predictions = bigram_pipeline.predict(X_test)
bigram_accuracy = accuracy_score(y_test, bigram_predictions)

print("Accuracy for bigram using Bag of words:", bigram_accuracy)
print(classification_report(y_test,bigram_predictions))

Accuracy for unigram using Bag of words: 0.6719457013574661
              precision    recall  f1-score   support

    negative       0.67      0.83      0.74       394
     neutral       0.43      0.15      0.23       170
    positive       0.72      0.75      0.74       320

    accuracy                           0.67       884
   macro avg       0.61      0.58      0.57       884
weighted avg       0.64      0.67      0.64       884

Accuracy for bigram using Bag of words: 0.6447963800904978
              precision    recall  f1-score   support

    negative       0.61      0.91      0.73       394
     neutral       0.47      0.12      0.20       170
    positive       0.77      0.59      0.67       320

    accuracy                           0.64       884
   macro avg       0.61      0.54      0.53       884
weighted avg       0.64      0.64      0.60       884

In [11]:

X_train = df1['content_hindi']
y_train = df1['new_rating']
X_test = df1_test['content_hindi']
y_test = df1_test['new_rating']

# Define pipelines for unigram and bigram features
unigram_pipeline = make_pipeline(TfidfVectorizer(ngram_range=(1, 1)), LogisticRegression(max_iter=1000))
bigram_pipeline = make_pipeline(TfidfVectorizer(ngram_range=(2, 2)), LogisticRegression(max_iter=1000))

# Fit and predict using unigram features
unigram_pipeline.fit(X_train, y_train)
unigram_predictions = unigram_pipeline.predict(X_test)
unigram_accuracy = accuracy_score(y_test, unigram_predictions)

print("Accuracy for unigram using Tfidf:", unigram_accuracy)
print(classification_report(y_test,unigram_predictions))

# Fit and predict using bigram features
bigram_pipeline.fit(X_train, y_train)
bigram_predictions = bigram_pipeline.predict(X_test)
bigram_accuracy = accuracy_score(y_test, bigram_predictions)

print("Accuracy for bigram using Tfidf:", bigram_accuracy)
print(classification_report(y_test,bigram_predictions))

Accuracy for unigram using Tfidf: 0.6640271493212669
              precision    recall  f1-score   support

    negative       0.66      0.82      0.73       394
     neutral       0.38      0.12      0.19       170
    positive       0.71      0.76      0.73       320

    accuracy                           0.66       884
   macro avg       0.59      0.57      0.55       884
weighted avg       0.63      0.66      0.63       884

Accuracy for bigram using Tfidf: 0.6979638009049773
              precision    recall  f1-score   support

    negative       0.66      0.90      0.77       394
     neutral       0.82      0.11      0.19       170
    positive       0.74      0.76      0.75       320

    accuracy                           0.70       884
   macro avg       0.74      0.59      0.57       884
weighted avg       0.72      0.70      0.65       884

In [12]:

X_train = df1['content_hindi']
y_train = df1['new_rating']
X_test = df1_test['content_hindi']
y_test = df1_test['new_rating']

# Define pipelines for unigram and bigram features
unigram_pipeline = make_pipeline(CountVectorizer(ngram_range=(1, 1)), LogisticRegression(max_iter=1000))
bigram_pipeline = make_pipeline(CountVectorizer(ngram_range=(2, 2)), LogisticRegression(max_iter=1000))

# Fit and predict using unigram features
unigram_pipeline.fit(X_train, y_train)
unigram_predictions = unigram_pipeline.predict(X_test)
unigram_accuracy = accuracy_score(y_test, unigram_predictions)

print("Accuracy for unigram using Bag of words:", unigram_accuracy)
print(classification_report(y_test,unigram_predictions))

# Fit and predict using bigram features
bigram_pipeline.fit(X_train, y_train)
bigram_predictions = bigram_pipeline.predict(X_test)
bigram_accuracy = accuracy_score(y_test, bigram_predictions)

print("Accuracy for bigram using Bag of words:", bigram_accuracy)
print(classification_report(y_test,bigram_predictions))

Accuracy for unigram using Bag of words: 0.6481900452488688
              precision    recall  f1-score   support

    negative       0.67      0.78      0.72       394
     neutral       0.35      0.20      0.25       170
    positive       0.70      0.72      0.71       320

    accuracy                           0.65       884
   macro avg       0.57      0.57      0.56       884
weighted avg       0.62      0.65      0.63       884

Accuracy for bigram using Bag of words: 0.668552036199095
              precision    recall  f1-score   support

    negative       0.71      0.79      0.75       394
     neutral       0.46      0.22      0.30       170
    positive       0.66      0.76      0.71       320

    accuracy                           0.67       884
   macro avg       0.61      0.59      0.59       884
weighted avg       0.65      0.67      0.65       884

In [13]:
df1['concatenated'] = df1['title_hindi'] + ' ' + df1['content_hindi']
df1_test['concatenated'] = df1_test['title_hindi'] + ' ' + df1_test['content_hindi']

In [14]:

X_train = df1['concatenated']
y_train = df1['new_rating']
X_test = df1_test['concatenated']
y_test = df1_test['new_rating']

# Define pipelines for unigram and bigram features
unigram_pipeline = make_pipeline(TfidfVectorizer(ngram_range=(1, 1)), LogisticRegression(max_iter=1000))
bigram_pipeline = make_pipeline(TfidfVectorizer(ngram_range=(2, 2)), LogisticRegression(max_iter=1000))

# Fit and predict using unigram features
unigram_pipeline.fit(X_train, y_train)
unigram_predictions = unigram_pipeline.predict(X_test)
unigram_accuracy = accuracy_score(y_test, unigram_predictions)

print("Accuracy for unigram using Bag of words:", unigram_accuracy)
print(classification_report(y_test,unigram_predictions))

# Fit and predict using bigram features
bigram_pipeline.fit(X_train, y_train)
bigram_predictions = bigram_pipeline.predict(X_test)
bigram_accuracy = accuracy_score(y_test, bigram_predictions)

print("Accuracy for bigram using Bag of words:", bigram_accuracy)
print(classification_report(y_test,bigram_predictions))

Accuracy for unigram using Bag of words: 0.7104072398190046
              precision    recall  f1-score   support

    negative       0.71      0.85      0.77       394
     neutral       0.46      0.18      0.26       170
    positive       0.76      0.82      0.79       320

    accuracy                           0.71       884
   macro avg       0.64      0.62      0.61       884
weighted avg       0.68      0.71      0.68       884

Accuracy for bigram using Bag of words: 0.7352941176470589
              precision    recall  f1-score   support

    negative       0.70      0.92      0.79       394
     neutral       0.81      0.12      0.21       170
    positive       0.79      0.84      0.81       320

    accuracy                           0.74       884
   macro avg       0.76      0.63      0.61       884
weighted avg       0.75      0.74      0.69       884

In [15]:

X_train = df1['concatenated']
y_train = df1['new_rating']
X_test = df1_test['concatenated']
y_test = df1_test['new_rating']

# Define pipelines for unigram and bigram features
unigram_pipeline = make_pipeline(CountVectorizer(ngram_range=(1, 1)), LogisticRegression(max_iter=1000))
bigram_pipeline = make_pipeline(CountVectorizer(ngram_range=(2, 2)), LogisticRegression(max_iter=1000))

# Fit and predict using unigram features
unigram_pipeline.fit(X_train, y_train)
unigram_predictions = unigram_pipeline.predict(X_test)
unigram_accuracy = accuracy_score(y_test, unigram_predictions)

print("Accuracy for unigram using Bag of words:", unigram_accuracy)
print(classification_report(y_test,unigram_predictions))

# Fit and predict using bigram features
bigram_pipeline.fit(X_train, y_train)
bigram_predictions = bigram_pipeline.predict(X_test)
bigram_accuracy = accuracy_score(y_test, bigram_predictions)

print("Accuracy for bigram using Bag of words:", bigram_accuracy)
print(classification_report(y_test,bigram_predictions))

Accuracy for unigram using Bag of words: 0.6866515837104072
              precision    recall  f1-score   support

    negative       0.72      0.79      0.75       394
     neutral       0.38      0.28      0.33       170
    positive       0.76      0.78      0.77       320

    accuracy                           0.69       884
   macro avg       0.62      0.62      0.62       884
weighted avg       0.67      0.69      0.68       884

Accuracy for bigram using Bag of words: 0.7262443438914027
              precision    recall  f1-score   support

    negative       0.74      0.84      0.79       394
     neutral       0.49      0.29      0.36       170
    positive       0.77      0.82      0.79       320

    accuracy                           0.73       884
   macro avg       0.67      0.65      0.65       884
weighted avg       0.71      0.73      0.71       884